name: Create Rancher PR

# This workflow triggers on a push to the main branch. It updates the
# rancher/shepherd dependency in the rancher/rancher repository by dispatching
# a downstream workflow.
on:
  push:
    branches:
      - main-demo-branch

jobs:
  dispatch-to-rancher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # This step generates an installation token for the rancher-rancher-pr-and-push GitHub App.
      # The token needs 'actions: write' permission on rancher/rancher to dispatch a workflow.
      - name: Generate token for rancher/rancher
        id: generate_token
        uses: tibdex/create-github-app-token@8b57193a49a366a338d5356359a21c314e0c453c # v1.10.0
        with:
          app_id: ${{ secrets.RANCHER_RANCHER_PR_APP_ID }}
          private_key: ${{ secrets.RANCHER_RANCHER_PR_PRIVATE_KEY }}
          owner: rancher
          repositories: rancher

      - name: Dispatch 'Go get' workflow in rancher/rancher
        run: |
          echo "Dispatching to rancher/rancher on branch main for shepherd commit ${{ github.sha }}"
          gh workflow run "Go get" \
            --repo rancher/rancher \
            --ref main \
            -F goget_module=github.com/rancher/shepherd \
            -F goget_version=${{ github.sha }} \
            -F source_author=${{ github.actor }}
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}