name: Create Rancher PR

# This workflow triggers on a push to the main branch. It updates the
# rancher/shepherd dependency in the rancher/rancher repository by dispatching
# a downstream workflow.
on:
  push:
    branches:
      - main-demo-branch

jobs:
  dispatch-to-rancher:
    permissions:
      # This is required for the vault action to get an OIDC token
      id-token: write
      # This is required to checkout the repository
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Retrieve token from vault
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/github-token/credentials token | PAT_TOKEN ;

      - name: Dispatch 'Go get' workflow in rancher/rancher
        run: |
          echo "Dispatching to rancher/rancher on branch main for shepherd commit ${{ github.sha }}"
          gh workflow run "Go get" \
            --repo rancher/rancher \
            --ref main \
            -F goget_module=github.com/rancher/shepherd \
            -F goget_version=${{ github.sha }} \
            -F source_author=${{ github.actor }}
        env:
          GH_TOKEN: ${{ env.PAT_TOKEN }}